# Generated by Django 5.2.1 on 2025-05-27 06:49

import echo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', echo.models.CustomUserManager()),
            ],
        ),
    ]
